version: '3.8'

services:
  ai-insights-db:
    image: postgres:13
    container_name: ai-insights-db_container
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "6001:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ai-insights-rabbitmq:
    image: rabbitmq:3-management
    container_name: ai-insights-rabbitmq_container
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "6002:5672"
      - "6003:15672"

  ai-insights-analyzer:
    build: ./data-analyzer
    container_name: ai-insights-analyzer
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ai-insights-db
      POSTGRES_PORT: 5432
      RABBITMQ_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: 5672
      GOOGLE_APPLICATION_CREDENTIALS: /app/gc-key.json
    volumes:
      - ./gc-key.json:/app/gc-key.json
    depends_on:
      - ai-insights-db
      - ai-insights-rabbitmq

  ai-insights-collector:
    build: ./data-collector
    container_name: ai-insights-collector
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ai-insights-db
      POSTGRES_PORT: 5432
      RABBITMQ_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: 5672
      BEARER_TOKEN: ${BEARER_TOKEN}
    depends_on:
      - ai-insights-db
      - ai-insights-rabbitmq

volumes:
  postgres_data:
